services:
  mad-science-scraper:
    build: .
    container_name: mad-science-scraper
    restart: unless-stopped
    environment:
      - SCRAPE_INTERVAL=300
    volumes:
      - ./config.yml:/usr/src/app/config.yml
      - ./latestVersion:/usr/src/app/latestVersion